# coding: utf-8

# flake8: noqa
"""
    OpenHolidays API v1

    Open Data API for public and school holidays

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from openholidays_python.models.country_reference import CountryReference
from openholidays_python.models.country_response import CountryResponse
from openholidays_python.models.group_reference import GroupReference
from openholidays_python.models.group_response import GroupResponse
from openholidays_python.models.holiday_by_date_response import HolidayByDateResponse
from openholidays_python.models.holiday_response import HolidayResponse
from openholidays_python.models.holiday_tags import HolidayTags
from openholidays_python.models.holiday_type import HolidayType
from openholidays_python.models.language_response import LanguageResponse
from openholidays_python.models.localized_text import LocalizedText
from openholidays_python.models.problem_details import ProblemDetails
from openholidays_python.models.regional_scope import RegionalScope
from openholidays_python.models.statistics_response import StatisticsResponse
from openholidays_python.models.subdivision_reference import SubdivisionReference
from openholidays_python.models.subdivision_response import SubdivisionResponse
from openholidays_python.models.temporal_scope import TemporalScope

