# coding: utf-8

"""
    OpenHolidays API v1

    Open Data API for public and school holidays

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from openholidays_python.models.group_reference import GroupReference
from openholidays_python.models.holiday_tags import HolidayTags
from openholidays_python.models.holiday_type import HolidayType
from openholidays_python.models.localized_text import LocalizedText
from openholidays_python.models.regional_scope import RegionalScope
from openholidays_python.models.subdivision_reference import SubdivisionReference
from openholidays_python.models.temporal_scope import TemporalScope
from typing import Optional, Set
from typing_extensions import Self

class HolidayResponse(BaseModel):
    """
    Representation of a holiday
    """ # noqa: E501
    comment: Optional[List[LocalizedText]] = Field(default=None, description="Additional localized comments")
    end_date: date = Field(description="End date of the holiday", alias="endDate")
    id: UUID = Field(description="Unique holiday id")
    name: List[LocalizedText] = Field(description="Localized names of the holiday")
    nationwide: StrictBool = Field(description="Is the holiday nationwide?")
    regional_scope: Optional[RegionalScope] = Field(default=None, alias="regionalScope")
    start_date: date = Field(description="Start date of the holiday", alias="startDate")
    subdivisions: Optional[List[SubdivisionReference]] = Field(default=None, description="List of subdivision references")
    groups: Optional[List[GroupReference]] = Field(default=None, description="List of group references")
    tags: Optional[HolidayTags] = None
    temporal_scope: Optional[TemporalScope] = Field(default=None, alias="temporalScope")
    type: HolidayType
    __properties: ClassVar[List[str]] = ["comment", "endDate", "id", "name", "nationwide", "regionalScope", "startDate", "subdivisions", "groups", "tags", "temporalScope", "type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HolidayResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in comment (list)
        _items = []
        if self.comment:
            for _item_comment in self.comment:
                if _item_comment:
                    _items.append(_item_comment.to_dict())
            _dict['comment'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in name (list)
        _items = []
        if self.name:
            for _item_name in self.name:
                if _item_name:
                    _items.append(_item_name.to_dict())
            _dict['name'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in subdivisions (list)
        _items = []
        if self.subdivisions:
            for _item_subdivisions in self.subdivisions:
                if _item_subdivisions:
                    _items.append(_item_subdivisions.to_dict())
            _dict['subdivisions'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in groups (list)
        _items = []
        if self.groups:
            for _item_groups in self.groups:
                if _item_groups:
                    _items.append(_item_groups.to_dict())
            _dict['groups'] = _items
        # set to None if comment (nullable) is None
        # and model_fields_set contains the field
        if self.comment is None and "comment" in self.model_fields_set:
            _dict['comment'] = None

        # set to None if subdivisions (nullable) is None
        # and model_fields_set contains the field
        if self.subdivisions is None and "subdivisions" in self.model_fields_set:
            _dict['subdivisions'] = None

        # set to None if groups (nullable) is None
        # and model_fields_set contains the field
        if self.groups is None and "groups" in self.model_fields_set:
            _dict['groups'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HolidayResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "comment": [LocalizedText.from_dict(_item) for _item in obj["comment"]] if obj.get("comment") is not None else None,
            "endDate": obj.get("endDate"),
            "id": obj.get("id"),
            "name": [LocalizedText.from_dict(_item) for _item in obj["name"]] if obj.get("name") is not None else None,
            "nationwide": obj.get("nationwide"),
            "regionalScope": obj.get("regionalScope"),
            "startDate": obj.get("startDate"),
            "subdivisions": [SubdivisionReference.from_dict(_item) for _item in obj["subdivisions"]] if obj.get("subdivisions") is not None else None,
            "groups": [GroupReference.from_dict(_item) for _item in obj["groups"]] if obj.get("groups") is not None else None,
            "tags": obj.get("tags"),
            "temporalScope": obj.get("temporalScope"),
            "type": obj.get("type")
        })
        return _obj


