# coding: utf-8

"""
    OpenHolidays API v1

    Open Data API for public and school holidays

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openholidays_python.models.group_reference import GroupReference
from openholidays_python.models.localized_text import LocalizedText
from typing import Optional, Set
from typing_extensions import Self

class SubdivisionResponse(BaseModel):
    """
    Representation of a subdivision
    """ # noqa: E501
    category: List[LocalizedText] = Field(description="Localized categories of the subdivision")
    children: Optional[List[SubdivisionResponse]] = Field(default=None, description="Child subdivisions")
    code: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Subdivision code")
    comment: List[LocalizedText] = Field(description="Localized comments of the subdivision")
    groups: Optional[List[GroupReference]] = Field(default=None, description="List of group references")
    iso_code: Optional[StrictStr] = Field(default=None, description="ISO 3166-2 subdivision code (if defined)", alias="isoCode")
    name: List[LocalizedText] = Field(description="Localized names of the subdivision")
    official_languages: List[StrictStr] = Field(description="Official languages as ISO-639-1 codes", alias="officialLanguages")
    short_name: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Short name for display", alias="shortName")
    __properties: ClassVar[List[str]] = ["category", "children", "code", "comment", "groups", "isoCode", "name", "officialLanguages", "shortName"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SubdivisionResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in category (list)
        _items = []
        if self.category:
            for _item_category in self.category:
                if _item_category:
                    _items.append(_item_category.to_dict())
            _dict['category'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in children (list)
        _items = []
        if self.children:
            for _item_children in self.children:
                if _item_children:
                    _items.append(_item_children.to_dict())
            _dict['children'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in comment (list)
        _items = []
        if self.comment:
            for _item_comment in self.comment:
                if _item_comment:
                    _items.append(_item_comment.to_dict())
            _dict['comment'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in groups (list)
        _items = []
        if self.groups:
            for _item_groups in self.groups:
                if _item_groups:
                    _items.append(_item_groups.to_dict())
            _dict['groups'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in name (list)
        _items = []
        if self.name:
            for _item_name in self.name:
                if _item_name:
                    _items.append(_item_name.to_dict())
            _dict['name'] = _items
        # set to None if children (nullable) is None
        # and model_fields_set contains the field
        if self.children is None and "children" in self.model_fields_set:
            _dict['children'] = None

        # set to None if groups (nullable) is None
        # and model_fields_set contains the field
        if self.groups is None and "groups" in self.model_fields_set:
            _dict['groups'] = None

        # set to None if iso_code (nullable) is None
        # and model_fields_set contains the field
        if self.iso_code is None and "iso_code" in self.model_fields_set:
            _dict['isoCode'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SubdivisionResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "category": [LocalizedText.from_dict(_item) for _item in obj["category"]] if obj.get("category") is not None else None,
            "children": [SubdivisionResponse.from_dict(_item) for _item in obj["children"]] if obj.get("children") is not None else None,
            "code": obj.get("code"),
            "comment": [LocalizedText.from_dict(_item) for _item in obj["comment"]] if obj.get("comment") is not None else None,
            "groups": [GroupReference.from_dict(_item) for _item in obj["groups"]] if obj.get("groups") is not None else None,
            "isoCode": obj.get("isoCode"),
            "name": [LocalizedText.from_dict(_item) for _item in obj["name"]] if obj.get("name") is not None else None,
            "officialLanguages": obj.get("officialLanguages"),
            "shortName": obj.get("shortName")
        })
        return _obj

# TODO: Rewrite to not use raise_errors
SubdivisionResponse.model_rebuild(raise_errors=False)

