# coding: utf-8

"""
    OpenHolidays API v1

    Open Data API for public and school holidays

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.statistics_api import StatisticsApi


class TestStatisticsApi(unittest.TestCase):
    """StatisticsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StatisticsApi()

    def tearDown(self) -> None:
        pass

    def test_statistics_public_holidays_get(self) -> None:
        """Test case for statistics_public_holidays_get

        Returns statistical data about public holidays for a given country.
        """
        pass

    def test_statistics_school_holidays_get(self) -> None:
        """Test case for statistics_school_holidays_get

        Returns statistical data about school holidays for a given country
        """
        pass


if __name__ == '__main__':
    unittest.main()
