# coding: utf-8

"""
    OpenHolidays API v1

    Open Data API for public and school holidays

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.temporal_scope import TemporalScope

class TestTemporalScope(unittest.TestCase):
    """TemporalScope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTemporalScope(self):
        """Test TemporalScope"""
        # inst = TemporalScope()

if __name__ == '__main__':
    unittest.main()
