# coding: utf-8

"""
    OpenHolidays API v1

    Open Data API for public and school holidays

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.holiday_type import HolidayType

class TestHolidayType(unittest.TestCase):
    """HolidayType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHolidayType(self):
        """Test HolidayType"""
        # inst = HolidayType()

if __name__ == '__main__':
    unittest.main()
