# coding: utf-8

"""
    OpenHolidays API v1

    Open Data API for public and school holidays

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.statistics_response import StatisticsResponse

class TestStatisticsResponse(unittest.TestCase):
    """StatisticsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatisticsResponse:
        """Test StatisticsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatisticsResponse`
        """
        model = StatisticsResponse()
        if include_optional:
            return StatisticsResponse(
                youngest_start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                oldest_start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date()
            )
        else:
            return StatisticsResponse(
                youngest_start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                oldest_start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
        )
        """

    def testStatisticsResponse(self):
        """Test StatisticsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
