# coding: utf-8

"""
    OpenHolidays API v1

    Open Data API for public and school holidays

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.holiday_by_date_response import HolidayByDateResponse

class TestHolidayByDateResponse(unittest.TestCase):
    """HolidayByDateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HolidayByDateResponse:
        """Test HolidayByDateResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HolidayByDateResponse`
        """
        model = HolidayByDateResponse()
        if include_optional:
            return HolidayByDateResponse(
                comment = [
                    openapi_client.models.localized_text.LocalizedText(
                        language = '0', 
                        text = '0', )
                    ],
                country = openapi_client.models.country_reference.CountryReference(
                    iso_code = 'DE', ),
                groups = [
                    openapi_client.models.group_reference.GroupReference(
                        code = 'FR-ZA', 
                        short_name = 'ZA', )
                    ],
                id = 'ff3b77a3-8c31-47af-b1c7-f26dd51f3c19',
                name = [
                    openapi_client.models.localized_text.LocalizedText(
                        language = '0', 
                        text = '0', )
                    ],
                nationwide = True,
                regional_scope = 'National',
                subdivisions = [
                    openapi_client.models.subdivision_reference.SubdivisionReference(
                        code = 'DE-BE', 
                        short_name = 'BE', )
                    ],
                tags = 'Recommended',
                temporal_scope = 'FullDay',
                type = 'Public'
            )
        else:
            return HolidayByDateResponse(
                country = openapi_client.models.country_reference.CountryReference(
                    iso_code = 'DE', ),
                id = 'ff3b77a3-8c31-47af-b1c7-f26dd51f3c19',
                name = [
                    openapi_client.models.localized_text.LocalizedText(
                        language = '0', 
                        text = '0', )
                    ],
                nationwide = True,
                type = 'Public',
        )
        """

    def testHolidayByDateResponse(self):
        """Test HolidayByDateResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
