# coding: utf-8

"""
    OpenHolidays API v1

    Open Data API for public and school holidays

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.holiday_tags import HolidayTags

class TestHolidayTags(unittest.TestCase):
    """HolidayTags unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHolidayTags(self):
        """Test HolidayTags"""
        # inst = HolidayTags()

if __name__ == '__main__':
    unittest.main()
