# coding: utf-8

"""
    OpenHolidays API v1

    Open Data API for public and school holidays

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.holidays_api import HolidaysApi


class TestHolidaysApi(unittest.TestCase):
    """HolidaysApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HolidaysApi()

    def tearDown(self) -> None:
        pass

    def test_public_holidays_by_date_get(self) -> None:
        """Test case for public_holidays_by_date_get

        Returns a list of public holidays from all countries for a given date.
        """
        pass

    def test_public_holidays_get(self) -> None:
        """Test case for public_holidays_get

        Returns list of public holidays for a given country
        """
        pass

    def test_school_holidays_by_date_get(self) -> None:
        """Test case for school_holidays_by_date_get

        Returns a list of school holidays from all countries for a given date.
        """
        pass

    def test_school_holidays_get(self) -> None:
        """Test case for school_holidays_get

        Returns list of official school holidays for a given country
        """
        pass


if __name__ == '__main__':
    unittest.main()
