# coding: utf-8

"""
    OpenHolidays API v1

    Open Data API for public and school holidays

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.group_response import GroupResponse

class TestGroupResponse(unittest.TestCase):
    """GroupResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupResponse:
        """Test GroupResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupResponse`
        """
        model = GroupResponse()
        if include_optional:
            return GroupResponse(
                category = [{"language":"fr","text":"zone"},{"language":"de","text":"Zone"}],
                children = [
                    openapi_client.models.group_response.GroupResponse(
                        category = [{"language":"fr","text":"zone"},{"language":"de","text":"Zone"}], 
                        children = [
                            openapi_client.models.group_response.GroupResponse(
                                category = [{"language":"fr","text":"zone"},{"language":"de","text":"Zone"}], 
                                code = 'FR-ZA', 
                                comment = [
                                    openapi_client.models.localized_text.LocalizedText(
                                        language = '0', 
                                        text = '0', )
                                    ], 
                                name = [{"language":"fr","text":"Zone A"},{"language":"de","text":"Zone A"}], 
                                short_name = 'ZA', 
                                subdivisions = [
                                    openapi_client.models.subdivision_reference.SubdivisionReference(
                                        code = 'DE-BE', 
                                        short_name = 'BE', )
                                    ], )
                            ], 
                        code = 'FR-ZA', 
                        comment = [
                            openapi_client.models.localized_text.LocalizedText(
                                language = '0', 
                                text = '0', )
                            ], 
                        name = [{"language":"fr","text":"Zone A"},{"language":"de","text":"Zone A"}], 
                        short_name = 'ZA', 
                        subdivisions = [
                            openapi_client.models.subdivision_reference.SubdivisionReference(
                                code = 'DE-BE', 
                                short_name = 'BE', )
                            ], )
                    ],
                code = 'FR-ZA',
                comment = [
                    openapi_client.models.localized_text.LocalizedText(
                        language = '0', 
                        text = '0', )
                    ],
                name = [{"language":"fr","text":"Zone A"},{"language":"de","text":"Zone A"}],
                short_name = 'ZA',
                subdivisions = [
                    openapi_client.models.subdivision_reference.SubdivisionReference(
                        code = 'DE-BE', 
                        short_name = 'BE', )
                    ]
            )
        else:
            return GroupResponse(
                category = [{"language":"fr","text":"zone"},{"language":"de","text":"Zone"}],
                code = 'FR-ZA',
                comment = [
                    openapi_client.models.localized_text.LocalizedText(
                        language = '0', 
                        text = '0', )
                    ],
                name = [{"language":"fr","text":"Zone A"},{"language":"de","text":"Zone A"}],
                short_name = 'ZA',
        )
        """

    def testGroupResponse(self):
        """Test GroupResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
