# coding: utf-8

"""
    OpenHolidays API v1

    Open Data API for public and school holidays

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.subdivision_response import SubdivisionResponse

class TestSubdivisionResponse(unittest.TestCase):
    """SubdivisionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubdivisionResponse:
        """Test SubdivisionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubdivisionResponse`
        """
        model = SubdivisionResponse()
        if include_optional:
            return SubdivisionResponse(
                category = [{"language":"fr","text":"région"},{"language":"de","text":"Region"}],
                children = [
                    openapi_client.models.subdivision_response.SubdivisionResponse(
                        category = [{"language":"fr","text":"région"},{"language":"de","text":"Region"}], 
                        children = [
                            openapi_client.models.subdivision_response.SubdivisionResponse(
                                category = [{"language":"fr","text":"région"},{"language":"de","text":"Region"}], 
                                code = 'FR-BF', 
                                comment = [
                                    openapi_client.models.localized_text.LocalizedText(
                                        language = '0', 
                                        text = '0', )
                                    ], 
                                groups = [
                                    openapi_client.models.group_reference.GroupReference(
                                        code = 'FR-ZA', 
                                        short_name = 'ZA', )
                                    ], 
                                iso_code = 'FR-BFC', 
                                name = [{"language":"fr","text":"Bourgogne-Franche-Comté"}], 
                                official_languages = [
                                    ''
                                    ], 
                                short_name = 'BF', )
                            ], 
                        code = 'FR-BF', 
                        comment = [
                            openapi_client.models.localized_text.LocalizedText(
                                language = '0', 
                                text = '0', )
                            ], 
                        groups = [
                            openapi_client.models.group_reference.GroupReference(
                                code = 'FR-ZA', 
                                short_name = 'ZA', )
                            ], 
                        iso_code = 'FR-BFC', 
                        name = [{"language":"fr","text":"Bourgogne-Franche-Comté"}], 
                        official_languages = [
                            ''
                            ], 
                        short_name = 'BF', )
                    ],
                code = 'FR-BF',
                comment = [
                    openapi_client.models.localized_text.LocalizedText(
                        language = '0', 
                        text = '0', )
                    ],
                groups = [
                    openapi_client.models.group_reference.GroupReference(
                        code = 'FR-ZA', 
                        short_name = 'ZA', )
                    ],
                iso_code = 'FR-BFC',
                name = [{"language":"fr","text":"Bourgogne-Franche-Comté"}],
                official_languages = [
                    ''
                    ],
                short_name = 'BF'
            )
        else:
            return SubdivisionResponse(
                category = [{"language":"fr","text":"région"},{"language":"de","text":"Region"}],
                code = 'FR-BF',
                comment = [
                    openapi_client.models.localized_text.LocalizedText(
                        language = '0', 
                        text = '0', )
                    ],
                name = [{"language":"fr","text":"Bourgogne-Franche-Comté"}],
                official_languages = [
                    ''
                    ],
                short_name = 'BF',
        )
        """

    def testSubdivisionResponse(self):
        """Test SubdivisionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
