# coding: utf-8

"""
    OpenHolidays API v1

    Open Data API for public and school holidays

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.country_reference import CountryReference

class TestCountryReference(unittest.TestCase):
    """CountryReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CountryReference:
        """Test CountryReference
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CountryReference`
        """
        model = CountryReference()
        if include_optional:
            return CountryReference(
                iso_code = 'DE'
            )
        else:
            return CountryReference(
                iso_code = 'DE',
        )
        """

    def testCountryReference(self):
        """Test CountryReference"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
