# coding: utf-8

"""
    OpenHolidays API v1

    Open Data API for public and school holidays

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.language_response import LanguageResponse

class TestLanguageResponse(unittest.TestCase):
    """LanguageResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LanguageResponse:
        """Test LanguageResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LanguageResponse`
        """
        model = LanguageResponse()
        if include_optional:
            return LanguageResponse(
                iso_code = 'DE',
                name = [{"language":"DE","text":"Deutsch"},{"language":"EN","text":"German"}]
            )
        else:
            return LanguageResponse(
                iso_code = 'DE',
                name = [{"language":"DE","text":"Deutsch"},{"language":"EN","text":"German"}],
        )
        """

    def testLanguageResponse(self):
        """Test LanguageResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
