# coding: utf-8

"""
    OpenHolidays API v1

    Open Data API for public and school holidays

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.regional_api import RegionalApi


class TestRegionalApi(unittest.TestCase):
    """RegionalApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RegionalApi()

    def tearDown(self) -> None:
        pass

    def test_countries_get(self) -> None:
        """Test case for countries_get

        Returns a list of all supported countries
        """
        pass

    def test_groups_get(self) -> None:
        """Test case for groups_get

        Returns a list of relevant holiday groups for a supported country (if any)
        """
        pass

    def test_languages_get(self) -> None:
        """Test case for languages_get

        Returns a list of all used languages
        """
        pass

    def test_subdivisions_get(self) -> None:
        """Test case for subdivisions_get

        Returns a list of relevant subdivisions for a supported country (if any)
        """
        pass


if __name__ == '__main__':
    unittest.main()
