# coding: utf-8

"""
    OpenHolidays API v1

    Open Data API for public and school holidays

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.holiday_response import HolidayResponse

class TestHolidayResponse(unittest.TestCase):
    """HolidayResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HolidayResponse:
        """Test HolidayResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HolidayResponse`
        """
        model = HolidayResponse()
        if include_optional:
            return HolidayResponse(
                comment = [
                    openapi_client.models.localized_text.LocalizedText(
                        language = '0', 
                        text = '0', )
                    ],
                end_date = 'Sat Dec 31 00:00:00 UTC 2022',
                id = 'ff3b77a3-8c31-47af-b1c7-f26dd51f3c19',
                name = [
                    openapi_client.models.localized_text.LocalizedText(
                        language = '0', 
                        text = '0', )
                    ],
                nationwide = True,
                regional_scope = 'National',
                start_date = 'Sat Jan 01 00:00:00 UTC 2022',
                subdivisions = [
                    openapi_client.models.subdivision_reference.SubdivisionReference(
                        code = 'DE-BE', 
                        short_name = 'BE', )
                    ],
                groups = [
                    openapi_client.models.group_reference.GroupReference(
                        code = 'FR-ZA', 
                        short_name = 'ZA', )
                    ],
                tags = 'Recommended',
                temporal_scope = 'FullDay',
                type = 'Public'
            )
        else:
            return HolidayResponse(
                end_date = 'Sat Dec 31 00:00:00 UTC 2022',
                id = 'ff3b77a3-8c31-47af-b1c7-f26dd51f3c19',
                name = [
                    openapi_client.models.localized_text.LocalizedText(
                        language = '0', 
                        text = '0', )
                    ],
                nationwide = True,
                start_date = 'Sat Jan 01 00:00:00 UTC 2022',
                type = 'Public',
        )
        """

    def testHolidayResponse(self):
        """Test HolidayResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
