# coding: utf-8

# flake8: noqa
"""
    OpenHolidays API v1

    Open Data API for public and school holidays

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from openapi_client.models.country_reference import CountryReference
from openapi_client.models.country_response import CountryResponse
from openapi_client.models.group_reference import GroupReference
from openapi_client.models.group_response import GroupResponse
from openapi_client.models.holiday_by_date_response import HolidayByDateResponse
from openapi_client.models.holiday_response import HolidayResponse
from openapi_client.models.holiday_tags import HolidayTags
from openapi_client.models.holiday_type import HolidayType
from openapi_client.models.language_response import LanguageResponse
from openapi_client.models.localized_text import LocalizedText
from openapi_client.models.problem_details import ProblemDetails
from openapi_client.models.regional_scope import RegionalScope
from openapi_client.models.statistics_response import StatisticsResponse
from openapi_client.models.subdivision_reference import SubdivisionReference
from openapi_client.models.subdivision_response import SubdivisionResponse
from openapi_client.models.temporal_scope import TemporalScope

