# coding: utf-8

"""
    OpenHolidays API v1

    Open Data API for public and school holidays

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class HolidayTags(str, Enum):
    """
    Additional holiday tags
    """

    """
    allowed enum values
    """
    RECOMMENDED = 'Recommended'
    PROVISIONAL = 'Provisional'
    ONETIME = 'OneTime'
    EXCEPTION = 'Exception'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of HolidayTags from a JSON string"""
        return cls(json.loads(json_str))


