# coding: utf-8

# flake8: noqa

"""
    OpenHolidays API v1

    Open Data API for public and school holidays

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "HolidaysApi",
    "RegionalApi",
    "StatisticsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "CountryReference",
    "CountryResponse",
    "GroupReference",
    "GroupResponse",
    "HolidayByDateResponse",
    "HolidayResponse",
    "HolidayTags",
    "HolidayType",
    "LanguageResponse",
    "LocalizedText",
    "ProblemDetails",
    "RegionalScope",
    "StatisticsResponse",
    "SubdivisionReference",
    "SubdivisionResponse",
    "TemporalScope",
]

# import apis into sdk package
from openholidays_python.api.holidays_api import HolidaysApi as HolidaysApi
from openholidays_python.api.regional_api import RegionalApi as RegionalApi
from openholidays_python.api.statistics_api import StatisticsApi as StatisticsApi

# import ApiClient
from openholidays_python.api_response import ApiResponse as ApiResponse
from openholidays_python.api_client import ApiClient as ApiClient
from openholidays_python.configuration import Configuration as Configuration
from openholidays_python.exceptions import OpenApiException as OpenApiException
from openholidays_python.exceptions import ApiTypeError as ApiTypeError
from openholidays_python.exceptions import ApiValueError as ApiValueError
from openholidays_python.exceptions import ApiKeyError as ApiKeyError
from openholidays_python.exceptions import ApiAttributeError as ApiAttributeError
from openholidays_python.exceptions import ApiException as ApiException

# import models into sdk package
from openholidays_python.models.country_reference import CountryReference as CountryReference
from openholidays_python.models.country_response import CountryResponse as CountryResponse
from openholidays_python.models.group_reference import GroupReference as GroupReference
from openholidays_python.models.group_response import GroupResponse as GroupResponse
from openholidays_python.models.holiday_by_date_response import HolidayByDateResponse as HolidayByDateResponse
from openholidays_python.models.holiday_response import HolidayResponse as HolidayResponse
from openholidays_python.models.holiday_tags import HolidayTags as HolidayTags
from openholidays_python.models.holiday_type import HolidayType as HolidayType
from openholidays_python.models.language_response import LanguageResponse as LanguageResponse
from openholidays_python.models.localized_text import LocalizedText as LocalizedText
from openholidays_python.models.problem_details import ProblemDetails as ProblemDetails
from openholidays_python.models.regional_scope import RegionalScope as RegionalScope
from openholidays_python.models.statistics_response import StatisticsResponse as StatisticsResponse
from openholidays_python.models.subdivision_reference import SubdivisionReference as SubdivisionReference
from openholidays_python.models.subdivision_response import SubdivisionResponse as SubdivisionResponse
from openholidays_python.models.temporal_scope import TemporalScope as TemporalScope

