# coding: utf-8

"""
    OpenHolidays API v1

    Open Data API for public and school holidays

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class HolidayType(str, Enum):
    """
    Type of holiday
    """

    """
    allowed enum values
    """
    PUBLIC = 'Public'
    BANK = 'Bank'
    OPTIONAL = 'Optional'
    SCHOOL = 'School'
    BACKTOSCHOOL = 'BackToSchool'
    ENDOFLESSONS = 'EndOfLessons'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of HolidayType from a JSON string"""
        return cls(json.loads(json_str))


