# coding: utf-8

"""
    OpenHolidays API v1

    Open Data API for public and school holidays

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from datetime import date
from pydantic import Field, StrictStr
from typing import List, Optional
from typing_extensions import Annotated
from openholidays_python.models.holiday_by_date_response import HolidayByDateResponse
from openholidays_python.models.holiday_response import HolidayResponse

from openholidays_python.api_client import ApiClient, RequestSerialized
from openholidays_python.api_response import ApiResponse
from openholidays_python.rest import RESTResponseType


class HolidaysApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def public_holidays_by_date_get(
        self,
        var_date: Annotated[date, Field(description="Date of interest")],
        language_iso_code: Annotated[Optional[StrictStr], Field(description="ISO-639-1 code of a language or empty")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[HolidayByDateResponse]:
        """Returns a list of public holidays from all countries for a given date.


        :param var_date: Date of interest (required)
        :type var_date: date
        :param language_iso_code: ISO-639-1 code of a language or empty
        :type language_iso_code: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._public_holidays_by_date_get_serialize(
            var_date=var_date,
            language_iso_code=language_iso_code,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[HolidayByDateResponse]",
            '400': "ProblemDetails",
            '500': "ProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def public_holidays_by_date_get_with_http_info(
        self,
        var_date: Annotated[date, Field(description="Date of interest")],
        language_iso_code: Annotated[Optional[StrictStr], Field(description="ISO-639-1 code of a language or empty")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[HolidayByDateResponse]]:
        """Returns a list of public holidays from all countries for a given date.


        :param var_date: Date of interest (required)
        :type var_date: date
        :param language_iso_code: ISO-639-1 code of a language or empty
        :type language_iso_code: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._public_holidays_by_date_get_serialize(
            var_date=var_date,
            language_iso_code=language_iso_code,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[HolidayByDateResponse]",
            '400': "ProblemDetails",
            '500': "ProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def public_holidays_by_date_get_without_preload_content(
        self,
        var_date: Annotated[date, Field(description="Date of interest")],
        language_iso_code: Annotated[Optional[StrictStr], Field(description="ISO-639-1 code of a language or empty")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Returns a list of public holidays from all countries for a given date.


        :param var_date: Date of interest (required)
        :type var_date: date
        :param language_iso_code: ISO-639-1 code of a language or empty
        :type language_iso_code: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._public_holidays_by_date_get_serialize(
            var_date=var_date,
            language_iso_code=language_iso_code,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[HolidayByDateResponse]",
            '400': "ProblemDetails",
            '500': "ProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _public_holidays_by_date_get_serialize(
        self,
        var_date,
        language_iso_code,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if var_date is not None:
            if isinstance(var_date, date):
                _query_params.append(
                    (
                        'date',
                        var_date.strftime(
                            self.api_client.configuration.date_format
                        )
                    )
                )
            else:
                _query_params.append(('date', var_date))
            
        if language_iso_code is not None:
            
            _query_params.append(('languageIsoCode', language_iso_code))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json', 
                    'text/json', 
                    'text/plain', 
                    'text/csv', 
                    'application/problem+json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/PublicHolidaysByDate',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def public_holidays_get(
        self,
        country_iso_code: Annotated[StrictStr, Field(description="ISO 3166-1 code of the country")],
        valid_from: Annotated[date, Field(description="Start of the date range")],
        valid_to: Annotated[date, Field(description="End of the date range")],
        language_iso_code: Annotated[Optional[StrictStr], Field(description="ISO-639-1 code of a language or empty")] = None,
        subdivision_code: Annotated[Optional[StrictStr], Field(description="Code of the subdivision or empty")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[HolidayResponse]:
        """Returns list of public holidays for a given country


        :param country_iso_code: ISO 3166-1 code of the country (required)
        :type country_iso_code: str
        :param valid_from: Start of the date range (required)
        :type valid_from: date
        :param valid_to: End of the date range (required)
        :type valid_to: date
        :param language_iso_code: ISO-639-1 code of a language or empty
        :type language_iso_code: str
        :param subdivision_code: Code of the subdivision or empty
        :type subdivision_code: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._public_holidays_get_serialize(
            country_iso_code=country_iso_code,
            valid_from=valid_from,
            valid_to=valid_to,
            language_iso_code=language_iso_code,
            subdivision_code=subdivision_code,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[HolidayResponse]",
            '400': "ProblemDetails",
            '500': "ProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def public_holidays_get_with_http_info(
        self,
        country_iso_code: Annotated[StrictStr, Field(description="ISO 3166-1 code of the country")],
        valid_from: Annotated[date, Field(description="Start of the date range")],
        valid_to: Annotated[date, Field(description="End of the date range")],
        language_iso_code: Annotated[Optional[StrictStr], Field(description="ISO-639-1 code of a language or empty")] = None,
        subdivision_code: Annotated[Optional[StrictStr], Field(description="Code of the subdivision or empty")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[HolidayResponse]]:
        """Returns list of public holidays for a given country


        :param country_iso_code: ISO 3166-1 code of the country (required)
        :type country_iso_code: str
        :param valid_from: Start of the date range (required)
        :type valid_from: date
        :param valid_to: End of the date range (required)
        :type valid_to: date
        :param language_iso_code: ISO-639-1 code of a language or empty
        :type language_iso_code: str
        :param subdivision_code: Code of the subdivision or empty
        :type subdivision_code: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._public_holidays_get_serialize(
            country_iso_code=country_iso_code,
            valid_from=valid_from,
            valid_to=valid_to,
            language_iso_code=language_iso_code,
            subdivision_code=subdivision_code,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[HolidayResponse]",
            '400': "ProblemDetails",
            '500': "ProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def public_holidays_get_without_preload_content(
        self,
        country_iso_code: Annotated[StrictStr, Field(description="ISO 3166-1 code of the country")],
        valid_from: Annotated[date, Field(description="Start of the date range")],
        valid_to: Annotated[date, Field(description="End of the date range")],
        language_iso_code: Annotated[Optional[StrictStr], Field(description="ISO-639-1 code of a language or empty")] = None,
        subdivision_code: Annotated[Optional[StrictStr], Field(description="Code of the subdivision or empty")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Returns list of public holidays for a given country


        :param country_iso_code: ISO 3166-1 code of the country (required)
        :type country_iso_code: str
        :param valid_from: Start of the date range (required)
        :type valid_from: date
        :param valid_to: End of the date range (required)
        :type valid_to: date
        :param language_iso_code: ISO-639-1 code of a language or empty
        :type language_iso_code: str
        :param subdivision_code: Code of the subdivision or empty
        :type subdivision_code: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._public_holidays_get_serialize(
            country_iso_code=country_iso_code,
            valid_from=valid_from,
            valid_to=valid_to,
            language_iso_code=language_iso_code,
            subdivision_code=subdivision_code,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[HolidayResponse]",
            '400': "ProblemDetails",
            '500': "ProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _public_holidays_get_serialize(
        self,
        country_iso_code,
        valid_from,
        valid_to,
        language_iso_code,
        subdivision_code,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if country_iso_code is not None:
            
            _query_params.append(('countryIsoCode', country_iso_code))
            
        if valid_from is not None:
            if isinstance(valid_from, date):
                _query_params.append(
                    (
                        'validFrom',
                        valid_from.strftime(
                            self.api_client.configuration.date_format
                        )
                    )
                )
            else:
                _query_params.append(('validFrom', valid_from))
            
        if valid_to is not None:
            if isinstance(valid_to, date):
                _query_params.append(
                    (
                        'validTo',
                        valid_to.strftime(
                            self.api_client.configuration.date_format
                        )
                    )
                )
            else:
                _query_params.append(('validTo', valid_to))
            
        if language_iso_code is not None:
            
            _query_params.append(('languageIsoCode', language_iso_code))
            
        if subdivision_code is not None:
            
            _query_params.append(('subdivisionCode', subdivision_code))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json', 
                    'text/json', 
                    'text/plain', 
                    'text/calendar', 
                    'text/csv', 
                    'application/problem+json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/PublicHolidays',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def school_holidays_by_date_get(
        self,
        var_date: Annotated[date, Field(description="Date of interest")],
        language_iso_code: Annotated[Optional[StrictStr], Field(description="ISO-639-1 code of a language or empty")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[HolidayByDateResponse]:
        """Returns a list of school holidays from all countries for a given date.


        :param var_date: Date of interest (required)
        :type var_date: date
        :param language_iso_code: ISO-639-1 code of a language or empty
        :type language_iso_code: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._school_holidays_by_date_get_serialize(
            var_date=var_date,
            language_iso_code=language_iso_code,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[HolidayByDateResponse]",
            '400': "ProblemDetails",
            '500': "ProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def school_holidays_by_date_get_with_http_info(
        self,
        var_date: Annotated[date, Field(description="Date of interest")],
        language_iso_code: Annotated[Optional[StrictStr], Field(description="ISO-639-1 code of a language or empty")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[HolidayByDateResponse]]:
        """Returns a list of school holidays from all countries for a given date.


        :param var_date: Date of interest (required)
        :type var_date: date
        :param language_iso_code: ISO-639-1 code of a language or empty
        :type language_iso_code: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._school_holidays_by_date_get_serialize(
            var_date=var_date,
            language_iso_code=language_iso_code,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[HolidayByDateResponse]",
            '400': "ProblemDetails",
            '500': "ProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def school_holidays_by_date_get_without_preload_content(
        self,
        var_date: Annotated[date, Field(description="Date of interest")],
        language_iso_code: Annotated[Optional[StrictStr], Field(description="ISO-639-1 code of a language or empty")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Returns a list of school holidays from all countries for a given date.


        :param var_date: Date of interest (required)
        :type var_date: date
        :param language_iso_code: ISO-639-1 code of a language or empty
        :type language_iso_code: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._school_holidays_by_date_get_serialize(
            var_date=var_date,
            language_iso_code=language_iso_code,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[HolidayByDateResponse]",
            '400': "ProblemDetails",
            '500': "ProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _school_holidays_by_date_get_serialize(
        self,
        var_date,
        language_iso_code,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if var_date is not None:
            if isinstance(var_date, date):
                _query_params.append(
                    (
                        'date',
                        var_date.strftime(
                            self.api_client.configuration.date_format
                        )
                    )
                )
            else:
                _query_params.append(('date', var_date))
            
        if language_iso_code is not None:
            
            _query_params.append(('languageIsoCode', language_iso_code))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json', 
                    'text/json', 
                    'text/plain', 
                    'text/csv', 
                    'application/problem+json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/SchoolHolidaysByDate',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def school_holidays_get(
        self,
        country_iso_code: Annotated[StrictStr, Field(description="ISO 3166-1 code of the country")],
        valid_from: Annotated[date, Field(description="Start of the date range")],
        valid_to: Annotated[date, Field(description="End of the date range")],
        language_iso_code: Annotated[Optional[StrictStr], Field(description="ISO-639-1 code of a language or empty")] = None,
        subdivision_code: Annotated[Optional[StrictStr], Field(description="Code of the subdivision or empty")] = None,
        group_code: Annotated[Optional[StrictStr], Field(description="Code of a holiday group or empty")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[HolidayResponse]:
        """Returns list of official school holidays for a given country


        :param country_iso_code: ISO 3166-1 code of the country (required)
        :type country_iso_code: str
        :param valid_from: Start of the date range (required)
        :type valid_from: date
        :param valid_to: End of the date range (required)
        :type valid_to: date
        :param language_iso_code: ISO-639-1 code of a language or empty
        :type language_iso_code: str
        :param subdivision_code: Code of the subdivision or empty
        :type subdivision_code: str
        :param group_code: Code of a holiday group or empty
        :type group_code: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._school_holidays_get_serialize(
            country_iso_code=country_iso_code,
            valid_from=valid_from,
            valid_to=valid_to,
            language_iso_code=language_iso_code,
            subdivision_code=subdivision_code,
            group_code=group_code,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[HolidayResponse]",
            '400': "ProblemDetails",
            '500': "ProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def school_holidays_get_with_http_info(
        self,
        country_iso_code: Annotated[StrictStr, Field(description="ISO 3166-1 code of the country")],
        valid_from: Annotated[date, Field(description="Start of the date range")],
        valid_to: Annotated[date, Field(description="End of the date range")],
        language_iso_code: Annotated[Optional[StrictStr], Field(description="ISO-639-1 code of a language or empty")] = None,
        subdivision_code: Annotated[Optional[StrictStr], Field(description="Code of the subdivision or empty")] = None,
        group_code: Annotated[Optional[StrictStr], Field(description="Code of a holiday group or empty")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[HolidayResponse]]:
        """Returns list of official school holidays for a given country


        :param country_iso_code: ISO 3166-1 code of the country (required)
        :type country_iso_code: str
        :param valid_from: Start of the date range (required)
        :type valid_from: date
        :param valid_to: End of the date range (required)
        :type valid_to: date
        :param language_iso_code: ISO-639-1 code of a language or empty
        :type language_iso_code: str
        :param subdivision_code: Code of the subdivision or empty
        :type subdivision_code: str
        :param group_code: Code of a holiday group or empty
        :type group_code: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._school_holidays_get_serialize(
            country_iso_code=country_iso_code,
            valid_from=valid_from,
            valid_to=valid_to,
            language_iso_code=language_iso_code,
            subdivision_code=subdivision_code,
            group_code=group_code,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[HolidayResponse]",
            '400': "ProblemDetails",
            '500': "ProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def school_holidays_get_without_preload_content(
        self,
        country_iso_code: Annotated[StrictStr, Field(description="ISO 3166-1 code of the country")],
        valid_from: Annotated[date, Field(description="Start of the date range")],
        valid_to: Annotated[date, Field(description="End of the date range")],
        language_iso_code: Annotated[Optional[StrictStr], Field(description="ISO-639-1 code of a language or empty")] = None,
        subdivision_code: Annotated[Optional[StrictStr], Field(description="Code of the subdivision or empty")] = None,
        group_code: Annotated[Optional[StrictStr], Field(description="Code of a holiday group or empty")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Returns list of official school holidays for a given country


        :param country_iso_code: ISO 3166-1 code of the country (required)
        :type country_iso_code: str
        :param valid_from: Start of the date range (required)
        :type valid_from: date
        :param valid_to: End of the date range (required)
        :type valid_to: date
        :param language_iso_code: ISO-639-1 code of a language or empty
        :type language_iso_code: str
        :param subdivision_code: Code of the subdivision or empty
        :type subdivision_code: str
        :param group_code: Code of a holiday group or empty
        :type group_code: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._school_holidays_get_serialize(
            country_iso_code=country_iso_code,
            valid_from=valid_from,
            valid_to=valid_to,
            language_iso_code=language_iso_code,
            subdivision_code=subdivision_code,
            group_code=group_code,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[HolidayResponse]",
            '400': "ProblemDetails",
            '500': "ProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _school_holidays_get_serialize(
        self,
        country_iso_code,
        valid_from,
        valid_to,
        language_iso_code,
        subdivision_code,
        group_code,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if country_iso_code is not None:
            
            _query_params.append(('countryIsoCode', country_iso_code))
            
        if valid_from is not None:
            if isinstance(valid_from, date):
                _query_params.append(
                    (
                        'validFrom',
                        valid_from.strftime(
                            self.api_client.configuration.date_format
                        )
                    )
                )
            else:
                _query_params.append(('validFrom', valid_from))
            
        if valid_to is not None:
            if isinstance(valid_to, date):
                _query_params.append(
                    (
                        'validTo',
                        valid_to.strftime(
                            self.api_client.configuration.date_format
                        )
                    )
                )
            else:
                _query_params.append(('validTo', valid_to))
            
        if language_iso_code is not None:
            
            _query_params.append(('languageIsoCode', language_iso_code))
            
        if subdivision_code is not None:
            
            _query_params.append(('subdivisionCode', subdivision_code))
            
        if group_code is not None:
            
            _query_params.append(('groupCode', group_code))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json', 
                    'text/json', 
                    'text/plain', 
                    'text/calendar', 
                    'text/csv', 
                    'application/problem+json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/SchoolHolidays',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


